### ISSUE TITLE
Api Docs (Helping material) for self understanding

### ISSUE THREAD

**Issue by s2zaman** [cigano/MvcScaffolding#1]
Hi, there:
This is not an issue,
I was asking for 'helping material' , from where i can understand how to define CustomTemplate .
I searched for, but couldn't find the one which is easy to understand.
On what file type should i work to start for my custom template. i-e '.ps1' or '.t4'

**Comment by cigano** [comment]
Hello, @s2zaman. In my case, [I started with this post](http://blog.stevensanderson.com/2011/04/06/mvcscaffolding-overriding-the-t4-templates/). 

**.ps1** extension is not for templates. It is used for Powershell scripts execution. **.t4** is an extension for templates. See the link for more details.
